
[SupersonicTheme]
Name = "Catppuccin Mocha (Pink)"
Version = "0.2"
SupportsDark = true
SupportsLight = true


[LightColors]
PageBackground = "#EFF1F5FF"
ListHeader = "#DCE0E8FF"
PageHeader = "#E6E9EFFF"
Background = "#DCE0E8FF"
Button = "#E6E9EFFF"
DisabledButton = "#CCD0DAFF"
Disabled = "#4C4F69FF"
Error = "#D20F39FF"
Focus = "#EED9EDFF"
Foreground = "#4C4F69FF"
ForegroundOnError = "#EFF1F5FF"
ForegroundOnPrimary = "#EFF1F5FF"
ForegroundOnSuccess = "#EFF1F5FF"
ForegroundOnWarning = "#EFF1F5FF"
HeaderBackground = "#CCD0DAFF"
Hover = "#EFE5F1FF"
Hyperlink = "#EA76CBFF"
InputBackground = "#E6E9EFFF"
InputBorder = "#CCD0DAFF"
MenuBackground = "#E6E9EFFF"
OverlayBackground = "#E6E9EFFF"
Placeholder = "#7C7F93FF"
Pressed = "#CCD0DA66"
Primary = "#EA76CBFF"
ScrollBar = "#E6E9EF99"
Selection = "#EED3EBFF"
Separator = "#DCE0E8FF"
Success = "#40A02BFF"
Warning = "#DF8E1DFF"


[DarkColors]
PageBackground = "#1E1E2EFF"
ListHeader = "#11111BFF"
PageHeader = "#181825FF"
Background = "#11111BFF"
Button = "#181825FF"
DisabledButton = "#313244FF"
Disabled = "#CDD6F4FF"
Error = "#F38BA8FF"
Focus = "#493F53FF"
Foreground = "#CDD6F4FF"
ForegroundOnError = "#1E1E2EFF"
ForegroundOnPrimary = "#1E1E2EFF"
ForegroundOnSuccess = "#1E1E2EFF"
ForegroundOnWarning = "#1E1E2EFF"
HeaderBackground = "#313244FF"
Hover = "#332E40FF"
Hyperlink = "#F5C2E7FF"
InputBackground = "#181825FF"
InputBorder = "#313244FF"
MenuBackground = "#181825FF"
OverlayBackground = "#181825FF"
Placeholder = "#9399B2FF"
Pressed = "#31324466"
Primary = "#F5C2E7FF"
ScrollBar = "#18182599"
Selection = "#53475CFF"
Separator = "#11111BFF"
Success = "#A6E3A1FF"
Warning = "#F9E2AFFF"
